# -*- coding: utf-8 -*-
"""collect_submission.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-M0Sd3XiJSUh-ECEfL0_rpAPhVPRkGO1
"""

from google.colab import drive

drive.mount('/content/drive')

# TODO: Enter the path in your Drive of the assignment.
# e.g. 'cs231n/assignments/assignment3/'
FOLDERNAME = 'Colab Notebooks/euron/cs231n/assignment3'

assert FOLDERNAME is not None, "[!] Enter the foldername."

"""# Collect Submission - Zip + Generate PDF 

<font color="red">**Note:** Remember to execute ALL notebooks' cells before this step. We won't be regrading missing cell outputs.</font>

Run this notebook once you have completed all the other notebooks.

It will:

* Generate a zip file of your code (`.py` and `.ipynb`) called `a3_code_submission.zip`.
* Convert all notebooks into a single PDF file called `a3_inline_submission.pdf`.

If your submission for this step was successful, you should see the following display message:

`### Done! Please submit a3_code_submission.zip and a3_inline_submission.pdf to Gradescope. ###`

Make sure to download the zip and pdf file locally to your computer, then submit to Gradescope. Congrats on successfully completing the assignment!
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/My\ Drive/$FOLDERNAME
!sudo apt-get update
!sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-generic-recommended
!pip install PyPDF2
!bash collectSubmission.sh